# Generated by Django 4.2.28 on 2026-02-23 13:17

from django.db import migrations


def set_ordered_at_for_existing_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(ordered_at__isnull=True):
        order.ordered_at = order.created_at
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancelled_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_ordered_at_for_existing_orders),
    ]
